// Generated by CoffeeScript 1.6.3
var getSettings, setSettings;

console.log('----------bg-----------');

getSettings = function() {
  var settings;
  settings = localStorage.getItem('settings');
  if (settings) {
    return JSON.parse(settings);
  } else {
    settings = {
      enabled: true
    };
    localStorage.setItem('settings', JSON.stringify(settings));
    return settings;
  }
};

chrome.browserAction.onClicked.addListener(function(tab) {
  return chrome.tabs.query({
    active: true,
    currentWindow: true
  }, function(tabs) {
    return chrome.tabs.sendMessage(tabs[0].id, {
      type: "hello",
      name: 'sam'
    }, function(response) {
      return console.log(response);
    });
  });
});

chrome.extension.onMessage.addListener(function(request, sender, cb) {
  if (request.type === 'getSettings') {
    return cb(getSettings());
  }
});

$(function() {
  var settings;
  settings = getSettings();
  if (settings.enabled) {
    $("#options").show();
    $("#cb_active").attr('checked', 'checked');
  } else {
    $("#options").hide();
    $("#cb_active").removeAttr('checked');
  }
  $("#filter").val(settings.filter);
  $("#cb_active").click(function() {
    if ($("#cb_active").is(":checked")) {
      $("#options").slideDown();
    } else {
      $("#options").slideUp();
    }
    return setSettings({
      enabled: $("#cb_active").is(":checked")
    });
  });
  return $("#btn_filetr").click(function() {
    return setSettings({
      filter: $("#filter").val()
    });
  });
});

setSettings = function(set) {
  return localStorage.setItem('settings', JSON.stringify($.extend(getSettings(), set)));
};
