// Generated by CoffeeScript 1.6.3
(function() {
  console.log('----------bg-----------');

  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      return chrome.tabs.sendMessage(tabs[0].id, {
        type: "hello",
        name: 'sam'
      }, function(response) {
        return console.log(response);
      });
    });
  });

  $(function() {
    return $("#cb_active").click(function() {
      if ($(this).is(":checked")) {
        return $("#filter").removeAttr('disabled');
      } else {
        return $("#filter").attr('disabled', 'disabled');
      }
    });
  });

}).call(this);
