// Generated by CoffeeScript 1.6.3
(function() {
  var settings;

  settings = {
    active: true
  };

  console.log('content');

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    console.log('msg');
    console.log((sender.tab ? "from a content script:" + sender.tab.url : "from the extension"));
    if (request.type === "hello") {
      alert('hi ' + request.name);
    }
    sendResponse({
      status: "ok"
    });
    return true;
  });

  $(function() {
    if (settings.active) {
      return $("h5").text('sam!');
    }
  });

}).call(this);
