// Generated by CoffeeScript 1.6.3
var settings;

settings = {
  active: true
};

console.log('content');

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
  console.log('msg');
  console.log((sender.tab ? "from a content script:" + sender.tab.url : "from the extension"));
  if (request.type === "hello") {
    alert('hi ' + request.name);
  }
  sendResponse({
    status: "ok"
  });
  return true;
});

$(function() {
  return chrome.runtime.sendMessage({
    type: "getSettings"
  }, function(settings) {
    var text;
    console.log("aa", settings);
    settings = settings;
    if (settings.enabled) {
      text = settings.filter;
      return $("a:contains('" + text + "'),p:contains('" + text + "'),span:contains('" + text + "')").each(function(i, e) {
        return $(e).attr('data-txt', $(e).text()).text('KABOOM').css({
          'background-color': 'red',
          'color': 'white'
        }).click(function() {
          return $(this).text($(this).attr('data-txt'));
        });
      });
    }
  });
});
